import { base } from '$app/paths';

// Loaded at prerender + during SPA nav. Both files are small (<5KB) and
// generated by the Rust pipeline; pulling them into `data` lets the page
// render statically with the values baked in.
export async function load({ fetch }) {
  const [statsRes, hpRes] = await Promise.all([
    fetch(`${base}/project-cube/assets/stats.json`),
    fetch(`${base}/project-cube/assets/hardpairs_manifest.json`),
  ]);
  if (!statsRes.ok) throw new Error(`stats.json: HTTP ${statsRes.status}`);
  if (!hpRes.ok) throw new Error(`hardpairs_manifest.json: HTTP ${hpRes.status}`);
  return {
    stats: await statsRes.json(),
    hardpairs: await hpRes.json(),
  };
}
